# Generated by Django 5.0.6 on 2025-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudingreso',
            name='codigo_ingreso',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
