# Generated by Django 5.0.6 on 2025-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_solicitud_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='identificador',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
