# Generated by Django 5.0.6 on 2024-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_registro_formulario_tipo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_formulario',
            name='tipo_proveedor',
            field=models.CharField(max_length=20),
        ),
    ]
