# Generated by Django 5.0.6 on 2025-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0017_registro_formulario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_formulario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
