# Generated by Django 5.0.6 on 2025-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0018_registro_formulario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestas_sol',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
