# Generated by Django 5.0.6 on 2025-07-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0020_certificaciones_proveedores_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicion_accionaria',
            name='tipo_identificacion',
            field=models.CharField(max_length=50),
        ),
    ]
